#!/usr/bin/env bash
# Build & package the AI Chat macOS app (modern Swift / SwiftUI, macOS 14+).
#
# Requires Xcode 15+ / Swift 5.9+ (this project uses Swift Concurrency,
# NavigationSplitView, @main / App, and other macOS 14-only APIs).
#
# Usage:
#   ./build.sh                    # SPM build + package .app
#   ./build.sh --package          # also produce dist/AIChatApp.app bundle
#   ./build.sh --run              # build and launch the app
set -euo pipefail

APP_NAME="AIChatApp"
BUILD_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$BUILD_ROOT/Sources"
DIST_DIR="$BUILD_ROOT/dist"
APP_DIR="$DIST_DIR/$APP_NAME.app"

GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}==>${NC} $1"; }
warn()  { echo -e "${YELLOW}WARN:${NC} $1"; }
die()   { echo -e "${RED}ERROR:${NC} $1" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Toolchain check
# ---------------------------------------------------------------------------
SWIFT_VERSION_OK=$(swift --version 2>/dev/null | grep -cE "Swift version (5\.[9]|[6-9]\.)" || true)
if [ "$SWIFT_VERSION_OK" -eq 0 ]; then
  die "This project requires macOS 14+ SDK & Swift 5.9+ (Xcode 15+).\n
       Found: $(swift --version 2>/dev/null | head -1)\n
       Please build with Xcode 15+ (open Package.swift in Xcode, or run:\n
       swift build)
  "
fi

info "Building $APP_NAME (macOS 14+, Swift Concurrency)..."

# Build (debug) via SwiftPM.
swift build 2>&1 | tail -20

# ---------------------------------------------------------------------------
# Optional .app bundling (--package, --run)
# ---------------------------------------------------------------------------
DO_PACKAGE=0
DO_RUN=0
for arg in "$@"; do
  case "$arg" in
    --package) DO_PACKAGE=1 ;;
    --run)     DO_PACKAGE=1; DO_RUN=1 ;;
  esac
done

if [ "$DO_PACKAGE" -eq 1 ]; then
  info "Packaging .app bundle..."
  rm -rf "$APP_DIR"
  mkdir -p "$APP_DIR/Contents/MacOS" "$APP_DIR/Contents/Resources"

  # Locate the SPM-built binary.
  BIN_PATH="$BUILD_ROOT/.build/debug/$APP_NAME"
  if [ ! -f "$BIN_PATH" ]; then
    die "Binary not found at $BIN_PATH — did 'swift build' succeed?"
  fi
  cp "$BIN_PATH" "$APP_DIR/Contents/MacOS/$APP_NAME"
  cp "$BUILD_ROOT/Info.plist" "$APP_DIR/Contents/Info.plist"

  # Copy SwiftPM resource bundles (SwiftMath's math fonts) next to the binary
  # so the packaged app can rasterize LaTeX. Bundle.module looks them up in
  # Contents/Resources at runtime.
  for bundle in "$BUILD_ROOT"/.build/debug/*.bundle; do
    if [ -e "$bundle" ]; then
      cp -R "$bundle" "$APP_DIR/Contents/Resources/"
    fi
  done

  # Copy the app icon if present (generated by scripts/generate_icon.swift).
  if [ -f "$BUILD_ROOT/Assets/AppIcon.icns" ]; then
    mkdir -p "$APP_DIR/Contents/Resources"
    cp "$BUILD_ROOT/Assets/AppIcon.icns" "$APP_DIR/Contents/Resources/AppIcon.icns"
  fi

  # Ad-hoc code signing so the app launches locally.
  codesign --force --deep --sign - "$APP_DIR" 2>/dev/null || \
    warn "codesign failed; app is still runnable locally."

  echo ""
  echo -e "${GREEN}Build complete!${NC}"
  echo "   App:     $APP_DIR"
  echo "   Binary:  $APP_DIR/Contents/MacOS/$APP_NAME"

  if [ "$DO_RUN" -eq 1 ]; then
    open "$APP_DIR"
  fi
else
  echo ""
  info "Build OK (debug)."
  echo "   Run with Xcode, or:  ./build.sh --package --run"
fi